### ISSUE TITLE
issuse in deploying

### ISSUE THREAD

**Issue by jafarisercan** [tusharsadhwani/piston_bot#14]
-bash: syntax error near unexpected token `newline'
Unable to read bot token. Make sure you export $TOKEN in the environment.

I receive such error in deploying on ubuntu server, what do I do?

**Comment by tusharsadhwani** [comment]
Hey,
you have to set `TOKEN` environment variable to your telegram bot token.

For example,

```
export TOKEN=abcd123_abcdedghij
go run ./cmd/bot
```

**Comment by jafarisercan** [comment]
> Hey, you have to set `TOKEN` environment variable to your telegram bot token.
> 
> For example,
> 
> ```
> export TOKEN=abcd123_abcdedghij
> go run ./cmd/bot
> ```
